### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by vysecurity** [Arno0x/NtlmRelayToEWS#1]
Worth logging the NetNTLMv2 hash?

https://github.com/sinnaj-r/NTLMssp-Extract

We can also use that in TCPDump I guess.

**Comment by Arno0x** [comment]
Hey Vincent,
In verbose mode, the NetNTLM hashes are logged on the screen so you can copy them for further cracking if required.

Good enough ?

**Comment by vysecurity** [comment]
Fab :D
